openapi: "3.0.3"

info:
  title: "Shop Review API"
  description: |
    # Features
    - Get Review
    - Post Review
  termsOfService: "https://tasty.com/terms/"
  contact:
    name: "Customer Support"
    url: "https://tasty.com/support/"
    email: "support@test.com"
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"
  version: "1.0.0"

servers:
  - url: "http://localhost:{port}"
    description: "local dev"
    variables:
      port:
        enum: ["3000", "8000"]
        default: "3000"
  - url: "https://itg.tasty.com"
    description: "Integration Test"
  - url: "https://stg.tasty.com"
    description: "Staging"
  - url: "https://api.tasty.com"
    description: "Production"

tags:
  - name: reviews
    description: "Shop review operation"

paths:
  "/shops/{shopId}/reviews":
    parameters:
      - name: shopId
        in: path
        required: true
        schema: { type: string }
        example: "abcdef"
    get:
      summary: "Get specified shop reviews"
      description: "Get specified shop reviews"
      tags: ["reviews"]
      deprecated: false
      responses:
        "200":
          description: "Success operation"
    post:
      deprecated: false
      summary: "Create reviews"
      tags: ["reviews"]
      parameters:
        - name: X-Api-Key
          in: header
          description: "Request user's identify"
          schema: { type: string }
          example: "XXXX-XXXX-XXXX"
        - name: token
          in: cookie
          description: "One time token"
          schema: { type: string }
          example: "XXXX-XXXX-XXXX"
      requestBody:
        description: "Contents of review"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                score: { type: integer, example: 3 }
                comment: { type: string, example: delicious }
      responses:
        "201":
          description: "Success operation"
          headers:
            location:
              description: "New URL of created review"
              schema: { type: string, format: url }
        "400":
          description: "Client side error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: string }
                  type: { type: string }
                  message: { type: string }
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field: { type: string }
                        code: { type: string }

components:
  schemas:
    SampleObject:
      type: object
      properties:
        shop:
          type: object
          properties:
            name: { type: string }
            place: { type: string }
        reviews:
          type: array
          items:
            type: object
            properties:
              score:
                type: integer
                enum: [1, 2, 3, 4, 5]
              comment:
                type: string

    SampleInt:
      type: integer
      minimum: 0
      exclusiveMinimum: false
      maximum: 100
      exclusiveMaximum: true
    SampleString:
      type: string
      nullable: true
      minLength: 10
      maxLength: 20
    SampleBoolean:
      type: boolean
